server:
  port: 7073

spring:
  application:
    name: products-api

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c5mccg6ukaka.ap-south-1.rds.amazonaws.com:3306/ecommerce
    username: admin
    password: admin321

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://admin-server:1111/

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
    register-with-eureka: true
    fetch-registry: true
app:
  images:
     upload-dir: D:\Study\E-Commerce\Product-Images\      
